const { PGlite } = require('../.dart_tool/commercial_sql_test/node_modules/@electric-sql/pglite');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const db = new PGlite();
  try {
    await db.exec(fs.readFileSync('test/fixtures/nc_base_schema.sql', 'utf8'));
    await db.exec(fs.readFileSync('supabase/migrations/20261001120000_catalogo_clientes.sql', 'utf8'));
    await db.exec(fs.readFileSync('supabase/migrations/20261001130000_catalogo_vigencia_12h.sql', 'utf8'));
    await db.exec("create function public.actualizar_pedido_activo(uuid,numeric,text,text,text,date,jsonb) returns void language plpgsql security definer as $$ begin null; end $$; grant execute on function public.actualizar_pedido_activo(uuid,numeric,text,text,text,date,jsonb) to anon,authenticated;");
    await db.exec(fs.readFileSync('supabase/migrations/20261001121000_catalogo_limita_rpc_internas.sql', 'utf8'));
    // Reproducir las antiguas políticas permisivas para verificar el cierre.
    await db.exec("grant usage on schema public,auth to authenticated; grant select,insert on clientes,productos to authenticated; grant select on usuarios to authenticated; create policy clientes_auth on clientes to authenticated using(true) with check(true); create policy productos_auth on productos to authenticated using(true) with check(true); create policy usuarios_auth on usuarios to authenticated using(true);");
    await db.exec(fs.readFileSync('supabase/migrations/20261001122000_catalogo_acceso_personal_activo.sql', 'utf8'));
    for(const f of ['test/fixtures/catalogo_storage_schema.sql','supabase/migrations/20261001140000_productos_fotos.sql','supabase/migrations/20261001141000_catalogo_preventista.sql','supabase/migrations/20261001142000_catalogo_asignacion_relacion.sql']) await db.exec(fs.readFileSync(f,'utf8'));
    const one = async (sql, args = []) => (await db.query(sql, args)).rows[0];
    assert.equal((await one("select has_function_privilege('anon','public.actualizar_pedido_activo(uuid,numeric,text,text,text,date,jsonb)','EXECUTE') allowed")).allowed,false);
    assert.equal((await one("select has_function_privilege('authenticated','public.actualizar_pedido_activo(uuid,numeric,text,text,text,date,jsonb)','EXECUTE') allowed")).allowed,true);
    const admin = '00000000-0000-0000-0000-000000000001';
    const seller = '00000000-0000-0000-0000-000000000002';
    await db.query("insert into usuarios(id,nombre,email,rol) values ($1,'Admin','a@test','administrador'),($2,'Seller','b@test','preventista')", [admin,seller]);
    await db.exec(`set test.uid='${admin}'`);
    const client = await one("insert into clientes(nombre_comercio,direccion) values ('Comercio','Privada') returning id");
    const p = await one("insert into productos(nombre,categoria,precio_normal,precio_promo,precio_interior,costo) values ('Papas Facu','Snacks',100,80,90,50) returning id");
    const food = await one("insert into productos(nombre,categoria,precio_normal,precio_promo,precio_interior) values ('Balanceado','Balanceados',300,200,250) returning id");
    await db.exec("insert into productos(nombre,visible_preventistas,precio_normal) values ('Oculto',false,500); insert into productos(nombre,activo,precio_normal) values ('Inactivo',false,500); insert into productos(nombre) values ('Sin precio');");
    const configure = async (base, cats={},prods={},renew=false,active=true) => (await one('select configurar_catalogo_cliente($1,$2,$3,$4,$5,$6) token', [client.id,base,JSON.stringify(cats),JSON.stringify(prods),renew,active])).token;
    const token = await configure('interior', {balanceados:'promo'}, {[p.id]:'normal'});
    assert.match(token,/^[a-f0-9]{64}$/);
    assert.notEqual((await one('select token_hash from catalogos_clientes')).token_hash, token);
    await db.exec('set role anon');
    const catalog = async token => (await one('select obtener_catalogo_cliente($1) c',[token])).c;
    const c = await catalog(token);
    assert.equal(c.nombre_comercio, 'Comercio'); assert.equal(c.productos.length,2);
    assert.equal(c.productos.find(x=>x.id===p.id).precio,100);
    assert.equal(c.productos.find(x=>x.id===food.id).precio,200);
    for (const x of c.productos) { assert.equal(x.costo,undefined); assert.equal(x.tipo,undefined); assert.equal(x.precio_interior,undefined); }
    await assert.rejects(db.query('select * from catalogos_clientes'),/permission denied/);
    await assert.rejects(db.query('select * from catalogo_productos_internos($1)',[client.id]),/permission denied/);
    await assert.rejects(catalog('f'.repeat(64)),/inválido/);
    const key = () => require('node:crypto').randomUUID();
    const submit = async (items,id=key()) => (await one('select crear_pedido_catalogo($1,$2,$3,$4) p',[token,id,JSON.stringify(items),'Entregar por la tarde'])).p;
    const cart = [{producto_id:p.id,cantidad:2,precio_visto:100},{producto_id:food.id,cantidad:1,precio_visto:200}];
    const request = key(); const order = await submit(cart,request);
    assert.equal(order.total,400); assert.deepEqual(await submit(cart,request),order);
    await assert.rejects(submit([{...cart[0],precio_visto:1}]),/precios cambiaron/);
    await assert.rejects(submit([{...cart[0],cantidad:-1}]),/Cantidad/);
    await assert.rejects(submit([{...cart[0],cantidad:1.5}]),/Cantidad/);
    await assert.rejects(submit([{...cart[0],cantidad:'NaN'}]),/Cantidad/);
    await assert.rejects(submit([cart[0],cart[0]]),/duplicado/);
    await assert.rejects(submit([{...cart[0],producto_id:key()}]),/disponible/);
    await assert.rejects(submit([]),/vacío/);
    await assert.rejects(submit([cart[0],{...cart[1],precio_visto:0}]),/precios cambiaron/);
    await db.exec('reset role');
    assert.equal(Number((await one('select count(*) n from pedidos')).n),1);
    assert.equal(Number((await one('select count(*) n from pedido_detalles')).n),2);
    const detail = await one('select * from pedido_detalles where producto_id=$1',[p.id]);
    assert.equal(Number(detail.costo_unitario),50); assert.equal(Number(detail.importe_comision),0); assert.equal(detail.tipo_precio,'normal');
    const stored = await one('select * from pedidos'); assert.equal(stored.preventista_id,admin); assert.equal(stored.estado,'pendiente'); assert.equal(stored.facturado,false);
    assert.match(stored.observacion,/Catálogo web/);
    assert.equal(stored.origen,'catalogo');
    await db.query('update pedido_detalles set porcentaje_comision=15,importe_comision=30 where pedido_id=$1',[order.pedido_id]);
    assert.equal(Number((await one('select sum(importe_comision) s from pedido_detalles')).s),0);
    assert.equal(await configure('normal', {balanceados:'promo'}, {}, false),null);
    await db.exec('set role anon'); assert.equal((await catalog(token)).productos.find(x=>x.id===p.id).precio,100); await db.exec('reset role');
    await db.query('update productos set precio_normal=101 where id=$1',[p.id]);
    await db.exec('set role anon'); await assert.rejects(submit(cart),/precios cambiaron/); await db.exec('reset role');
    const expiry = (await one('select vence_at from catalogos_clientes')).vence_at;
    assert.ok(new Date(expiry).getTime() > Date.now()+11.9*3600000);
    assert.ok(new Date(expiry).getTime() <= Date.now()+12*3600000);
    assert.equal(new Date((await catalog(token)).vence_at).getTime(),new Date(expiry).getTime());
    await configure('normal',{}, {}, false,true);
    assert.equal(new Date((await one('select vence_at from catalogos_clientes')).vence_at).getTime(),new Date(expiry).getTime());
    await db.exec("update catalogos_clientes set vence_at=clock_timestamp()-interval '1 second'");
    await db.exec('set role anon');
    await assert.rejects(catalog(token),/enlace venció/);
    await assert.rejects(submit(cart),/enlace venció/);
    await db.exec('reset role');
    assert.equal(Number((await one('select count(*) n from pedidos')).n),1);
    await configure('normal',{}, {}, false,false);
    await configure('normal',{}, {}, false,true);
    await assert.rejects(catalog(token),/enlace venció/);
    await configure('normal',{}, {}, false,false);
    await assert.rejects(catalog(token),/desactivado/); await assert.rejects(submit(cart,request),/desactivado/);
    const renewed=await configure('normal',{}, {}, true,true);
    await assert.rejects(catalog(token),/desactivado/); assert.ok((await catalog(renewed)).productos.length);
    await db.exec(`set role authenticated; set test.uid='${seller}'`);
    assert.ok((await db.query('select id from clientes')).rows.length>0);
    assert.ok((await db.query('select id from productos')).rows.length>0);
    await db.exec("set test.uid='00000000-0000-0000-0000-000000000099'");
    assert.equal((await db.query('select id from clientes')).rows.length,0);
    assert.equal((await db.query('select id from productos')).rows.length,0);
    assert.equal((await db.query('select id from usuarios')).rows.length,0);
    await assert.rejects(db.query("insert into clientes(nombre_comercio,direccion) values ('No autorizado','No autorizado')"),/row-level security/);
    await db.exec('reset role');
    await db.query('update usuarios set activo=false where id=$1',[seller]);
    await db.exec(`set role authenticated; set test.uid='${seller}'`);
    assert.equal((await db.query('select id from clientes')).rows.length,0);
    await db.exec('reset role');
    await db.query('update usuarios set activo=true where id=$1',[seller]);
    await db.exec(`set test.uid='${seller}'; set role authenticated`);
    await assert.rejects(configure('normal'),/administrador/);
    assert.equal((await db.query('select * from catalogos_clientes')).rows.length,0);
    await db.exec('reset role');
    await db.query('update clientes set activo=false where id=$1',[client.id]); await assert.rejects(catalog(renewed),/desactivado/);
    console.log('Catálogo SQL: precios mixtos, privacidad, RLS, pedidos atómicos, reintentos, validación y revocación OK.');
  } finally { await db.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
