const {PGlite}=require('../.dart_tool/commercial_sql_test/node_modules/@electric-sql/pglite');
const fs=require('node:fs'), assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
(async()=>{const db=new PGlite();try{
 const read=p=>fs.readFileSync(p,'utf8');
 const one=async(sql,args=[])=>(await db.query(sql,args)).rows[0];
 await db.exec(read('test/fixtures/nc_base_schema.sql'));
 await db.exec(read('supabase/migrations/20260928210000_notas_credito_internas.sql'));
 const editor=read('supabase/migrations/20260906185228_editor_pedidos_y_notificacion_edicion.sql');
 await db.exec(editor.slice(editor.indexOf('create or replace function public.actualizar_pedido_activo')));
 await db.exec('create function enviar_notificacion_pedido_editado(uuid,uuid) returns void language sql as $$ select $$');
 await db.exec(read('supabase/migrations/20260927032213_refuerza_eliminacion_pedido_pendiente.sql'));
 await db.exec(`grant usage on schema public,auth to authenticated,anon;
 grant all on all tables in schema public to authenticated;
 alter table clientes enable row level security; alter table pedidos enable row level security; alter table productos enable row level security;
 alter table pedido_detalles enable row level security; alter table pedido_pagos enable row level security;
 create policy clientes_auth on clientes to authenticated using(true) with check(true);
 create policy productos_auth on productos for select to authenticated using(true);
 create policy pedidos_auth on pedidos for select to authenticated using(true);
 create policy detalles_auth on pedido_detalles for select to authenticated using(true);
 create policy pagos_auth on pedido_pagos for select to authenticated using(true);
 create policy "usuarios autenticados pueden crear pedidos" on pedidos for insert to authenticated with check(true);
 create policy "usuarios autenticados pueden crear detalles de pedidos" on pedido_detalles for insert to authenticated with check(true);`);
 for(const f of ['20261001120000_catalogo_clientes.sql','20261001122000_catalogo_acceso_personal_activo.sql','20261001130000_catalogo_vigencia_12h.sql']) await db.exec(read('supabase/migrations/'+f));
 await db.exec(read('test/fixtures/catalogo_storage_schema.sql'));
 for(const f of ['20261001140000_productos_fotos.sql','20261001141000_catalogo_preventista.sql','20261001142000_catalogo_asignacion_relacion.sql'])await db.exec(read('supabase/migrations/'+f));
 if(process.env.SECURITY_PHASED === '1') {
   await db.exec(read('supabase/deployment/seguridad_01_preparacion.sql'));
   assert.equal((await one("select has_table_privilege('authenticated','productos','SELECT') allowed")).allowed,true);
   assert.equal((await one("select count(*)::int n from pg_policies where policyname in ('usuarios autenticados pueden crear pedidos','usuarios autenticados pueden crear detalles de pedidos')")).n,2);
   assert.ok((await one("select to_regprocedure('crear_pedido_interno(uuid,uuid,text,text,text,date,jsonb)') rpc")).rpc);
   await db.exec(read('supabase/deployment/seguridad_02_activacion.sql'));
 } else {
   await db.exec(read('supabase/migrations/20261002120000_permisos_preventistas.sql'));
 }
 const admin=randomUUID(),a=randomUUID(),b=randomUUID(),stranger=randomUUID();
 await db.query("insert into usuarios(id,nombre,email,rol) values($1,'Admin','a@test','administrador'),($2,'A','b@test','preventista'),($3,'B','c@test','preventista')",[admin,a,b]);
 const c=(await one("insert into clientes(nombre_comercio,direccion,preventista_id) values('Cliente','Direccion',$1) returning id",[a])).id;
 const other=(await one("insert into clientes(nombre_comercio,direccion,preventista_id) values('Otro','Direccion',$1) returning id",[b])).id;
 const prod=(await one("insert into productos(nombre,costo,precio_normal,precio_promo,precio_interior) values('Producto',50,100,80,90) returning id")).id;
 const login=async(id,role='authenticated')=>{await db.exec('reset role');await db.exec(`set test.uid='${id}'; set role ${role}`)};
 const cart=[{producto_id:prod,cantidad:2,tipo_precio:'normal',precio_unitario:100,costo_unitario:1,subtotal:1}];
 const create=async(id=randomUUID(),client=c,items=cart,type='pedido')=>(await one("select crear_pedido_interno($1,$2,'normal',$3,'',current_date,$4) id",[id,client,type,JSON.stringify(items)])).id;
 await login(a);
 assert.equal((await db.query('select id from clientes')).rows.length,1);
 await db.query("update clientes set nombre_comercio='Nuevo',direccion='Nueva',dia_visita=2,latitud=1 where id=$1",[c]);
 await assert.rejects(db.query('update clientes set preventista_id=$1 where id=$2',[b,c]),/asignación/);
 assert.equal((await db.query("update clientes set direccion='X' where id=$1 returning id",[other])).rows.length,0);
 for(const sql of ['select costo from productos','select costo_unitario from pedido_detalles','select costo from nota_credito_detalles','select * from productos'])await assert.rejects(db.query(sql),/permission denied/);
 assert.equal((await db.query('select precio_normal,precio_promo,precio_interior from productos')).rows.length,1);
 assert.equal((await db.query('select costo from productos_administracion')).rows.length,0);
 assert.equal((await one("select has_table_privilege('authenticated','pedidos','TRUNCATE') allowed")).allowed,false);
 const id=randomUUID();assert.equal(await create(id),id);assert.equal(await create(id),id);
 await assert.rejects(create(id,c,[{...cart[0],cantidad:3}]),/ya fue utilizada/);
 await assert.rejects(create(randomUUID(),other),/no asignado/);
 await assert.rejects(create(randomUUID(),c,[{...cart[0],precio_unitario:1}]),/precios cambiaron/);
 await assert.rejects(create(randomUUID(),c,[{...cart[0],cantidad:-1}]),/Cantidad/);
 await assert.rejects(db.query("insert into pedidos(cliente_id,preventista_id,tipo_precio) values($1,$2,'normal')",[c,b]),/row-level/);
 await assert.rejects(db.query('insert into pedido_detalles(pedido_id,producto_id,cantidad,precio_unitario,subtotal) values($1,$2,1,1,1)',[id,prod]),/row-level/);
 await login(admin);
 assert.equal((await db.query('select id from historial_cambios_clientes')).rows.length,1);
 assert.equal(Number((await one('select costo_unitario from detalles_administracion where pedido_id=$1',[id])).costo_unitario),50);
 assert.equal(Number((await one('select total from pedidos where id=$1',[id])).total),200);
 await db.query('update clientes set preventista_id=$1 where id=$2',[b,c]);
 await login(a);assert.equal((await db.query('select id from pedidos where id=$1',[id])).rows.length,1);
 assert.equal((await db.query('select id from historial_cambios_clientes')).rows.length,0);
 assert.equal((await db.query("update clientes set direccion='No' where id=$1 returning id",[c])).rows.length,0);
 await assert.rejects(create(),/no asignado/);
 await db.query("select actualizar_pedido_activo($1,1,'normal','pedido','',current_date,$2)",[id,JSON.stringify(cart)]);
 await login(b);assert.equal((await db.query('select id from pedidos where id=$1',[id])).rows.length,0);
 await assert.rejects(db.query("select actualizar_pedido_activo($1,1,'normal','pedido','',current_date,$2)",[id,JSON.stringify(cart)]),/no autorizado/);
 const newOrder=await create(randomUUID(),c,cart,'venta_directa');
 const deleted=await create();
 await db.query('select eliminar_pedido_pendiente($1)',[deleted]);
 await assert.rejects(create(deleted),/eliminado/);
 await login(admin);assert.equal((await one('select preventista_id from pedidos where id=$1',[id])).preventista_id,a);
 assert.equal((await one('select preventista_id from pedidos where id=$1',[newOrder])).preventista_id,b);
 // El catálogo sigue creando pedidos en el servidor y asignando la comisión elegida.
 const token=(await one("select configurar_catalogo_cliente_v2($1,'normal','{}','{}',true,true,$2) token",[c,b])).token;
 await login('', 'anon');
 const cat=(await one('select obtener_catalogo_cliente($1) c',[token])).c;assert.equal(cat.productos[0].costo,undefined);
 await db.query('select crear_pedido_catalogo($1,$2,$3)',[token,randomUUID(),JSON.stringify([{producto_id:prod,cantidad:1,precio_visto:100}])]);
 await assert.rejects(create(),/permission denied/);
 await db.exec('reset role');await db.query('update usuarios set activo=false where id=$1',[a]);
 await login(a);assert.equal((await db.query('select id from pedidos')).rows.length,0);
 await assert.rejects(db.query('select eliminar_pedido_pendiente($1)',[id]),/inactivo/);
 await assert.rejects(db.query("select actualizar_pedido_activo($1,1,'normal','pedido','',current_date,$2)",[id,JSON.stringify(cart)]),/inactivo/);
 await login(stranger);assert.equal((await db.query('select id from productos')).rows.length,0);await assert.rejects(create(),/inactivo/);
 console.log('OK: costos, clientes propios, historial tras reasignación, pedidos atómicos, reintentos, precios, usuarios inactivos y catálogo.');
}finally{await db.close()}})().catch(e=>{console.error(e);process.exitCode=1});
